function template(locals) {
var jade_debug = [{ lineno: 1, filename: "index.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (undefined) {
jade_debug.unshift({ lineno: 0, filename: "index.jade" });
jade_debug.unshift({ lineno: 1, filename: "index.jade" });
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "index.jade" });
buf.push("<html>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "index.jade" });
buf.push("<head>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: "index.jade" });
buf.push("<link href=\"http://fonts.googleapis.com/css?family=Righteous\" rel=\"stylesheet\" type=\"text/css\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "index.jade" });
buf.push("<style type=\"text/css\">");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push(".love {");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("\tfont-size: x-small;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("\tfont-weight: bold;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("}");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push(".middle {");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("\tmargin: 20px auto;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("\ttext-align: center;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("}");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("#totes-profesh {");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("\tfont-family: monospace;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("}");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("#we-are {");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("\tfont-family: 'Righteous', cursive;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("\tfont-size: large;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("}");
jade_debug.shift();
jade_debug.shift();
buf.push("</style>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "index.jade" });
buf.push("<title>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("Totes Profesh&#8482;");
jade_debug.shift();
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "index.jade" });
buf.push("<body>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: "index.jade" });
buf.push("<p id=\"we-are\" class=\"middle\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 8, filename: jade_debug[0].filename });
buf.push("We are");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "index.jade" });
buf.push("<pre id=\"totes-profesh\" title=\"Totes Profesh\" class=\"middle\">");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp; ________           __                                _______                       ______                     __       ");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp;/        |         /  |                              /       \\                     /      \\                   /  |      ");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp;$$$$$$$$/______   _$$ |_     ______    _______       $$$$$$$  | ______    ______  /$$$$$$  |______    _______ $$ |____  ");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp;   $$ | /      \\ / $$   |   /      \\  /       |      $$ |__$$ |/      \\  /      \\ $$ |_ $$//      \\  /       |$$      \\ ");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp;   $$ |/$$$$$$  |$$$$$$/   /$$$$$$  |/$$$$$$$/       $$    $$//$$$$$$  |/$$$$$$  |$$   |  /$$$$$$  |/$$$$$$$/ $$$$$$$  |");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp;   $$ |$$ |  $$ |  $$ | __ $$    $$ |$$      \\       $$$$$$$/ $$ |  $$/ $$ |  $$ |$$$$/   $$    $$ |$$      \\ $$ |  $$ |");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp;   $$ |$$ \\__$$ |  $$ |/  |$$$$$$$$/  $$$$$$  |      $$ |     $$ |      $$ \\__$$ |$$ |    $$$$$$$$/  $$$$$$  |$$ |  $$ |");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp;   $$ |$$    $$/   $$  $$/ $$       |/     $$/       $$ |     $$ |      $$    $$/ $$ |    $$       |/     $$/ $$ |  $$ |");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 9, filename: jade_debug[0].filename });
buf.push("&nbsp;   $$/  $$$$$$/     $$$$/   $$$$$$$/ $$$$$$$/        $$/      $$/        $$$$$$/  $$/      $$$$$$$/ $$$$$$$/  $$/   $$/ ");
jade_debug.shift();
jade_debug.shift();
buf.push("</pre>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "index.jade" });
buf.push("<!--");
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
buf.push("Thanks patorjk.com!");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
buf.push("http://patorjk.com/software/taag/#p=display&f=Big%20Money-sw&t=Totes%20Profesh");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 10, filename: jade_debug[0].filename });
buf.push("");
jade_debug.shift();
jade_debug.shift();
buf.push("-->");
jade_debug.shift();
jade_debug.unshift({ lineno: 11, filename: "index.jade" });
buf.push("<p class=\"love middle\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: jade_debug[0].filename });
buf.push("&lt;3");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 12, filename: "index.jade" });
buf.push("<p class=\"middle\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: jade_debug[0].filename });
buf.push("We engage social strategies to promote synergy towards success.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.shift();}.call(this,"undefined" in locals_for_with?locals_for_with.undefined:typeof undefined!=="undefined"?undefined:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype html\nhtml\n\thead\n\t\tlink(href=\"http://fonts.googleapis.com/css?family=Righteous\", rel=\"stylesheet\", type=\"text/css\")\n\t\tstyle(type=\"text/css\").\n\t\t\t.love {\n\t\t\t\tfont-size: x-small;\n\t\t\t\tfont-weight: bold;\n\t\t\t}\n\t\t\t.middle {\n\t\t\t\tmargin: 20px auto;\n\t\t\t\ttext-align: center;\n\t\t\t}\n\t\t\t#totes-profesh {\n\t\t\t\tfont-family: monospace;\n\t\t\t}\n\t\t\t#we-are {\n\t\t\t\tfont-family: 'Righteous', cursive;\n\t\t\t\tfont-size: large;\n\t\t\t}\n\t\ttitle Totes Profesh&#8482;\n\tbody\n\t\tp#we-are.middle We are\n\t\tpre#totes-profesh.middle(title=\"Totes Profesh\").\n\t\t\t&nbsp; ________           __                                _______                       ______                     __       \n\t\t\t&nbsp;/        |         /  |                              /       \\                     /      \\                   /  |      \n\t\t\t&nbsp;$$$$$$$$/______   _$$ |_     ______    _______       $$$$$$$  | ______    ______  /$$$$$$  |______    _______ $$ |____  \n\t\t\t&nbsp;   $$ | /      \\ / $$   |   /      \\  /       |      $$ |__$$ |/      \\  /      \\ $$ |_ $$//      \\  /       |$$      \\ \n\t\t\t&nbsp;   $$ |/$$$$$$  |$$$$$$/   /$$$$$$  |/$$$$$$$/       $$    $$//$$$$$$  |/$$$$$$  |$$   |  /$$$$$$  |/$$$$$$$/ $$$$$$$  |\n\t\t\t&nbsp;   $$ |$$ |  $$ |  $$ | __ $$    $$ |$$      \\       $$$$$$$/ $$ |  $$/ $$ |  $$ |$$$$/   $$    $$ |$$      \\ $$ |  $$ |\n\t\t\t&nbsp;   $$ |$$ \\__$$ |  $$ |/  |$$$$$$$$/  $$$$$$  |      $$ |     $$ |      $$ \\__$$ |$$ |    $$$$$$$$/  $$$$$$  |$$ |  $$ |\n\t\t\t&nbsp;   $$ |$$    $$/   $$  $$/ $$       |/     $$/       $$ |     $$ |      $$    $$/ $$ |    $$       |/     $$/ $$ |  $$ |\n\t\t\t&nbsp;   $$/  $$$$$$/     $$$$/   $$$$$$$/ $$$$$$$/        $$/      $$/        $$$$$$/  $$/      $$$$$$$/ $$$$$$$/  $$/   $$/ \n\t\t//\n\t\t\tThanks patorjk.com!\n\t\t\thttp://patorjk.com/software/taag/#p=display&f=Big%20Money-sw&t=Totes%20Profesh\n\n\t\tp.love.middle &lt;3\n\t\tp.middle We engage social strategies to promote synergy towards success.\n");
}
}